# Generated by Django 4.2.23 on 2025-08-06 01:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cart",
            unique_together={("user",), ("session_key",)},
        ),
    ]
