# Generated by Django 4.2.23 on 2025-08-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_remove_product_discount_active_and_more"),
        ("cart", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discountrule",
            name="discount",
        ),
        migrations.AlterModelOptions(
            name="cartitem",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="cart",
            name="discount",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="total_price",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="Цена"
            ),
        ),
        migrations.DeleteModel(
            name="Discount",
        ),
        migrations.DeleteModel(
            name="DiscountRule",
        ),
    ]
