# Generated by Django 4.2.23 on 2025-08-17 23:00

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_alter_product_price"),
        ("cart", "0003_remove_discountrule_discount_alter_cartitem_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Скидка", max_length=100, verbose_name="Название"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("product", "На товар"),
                            ("cart", "На корзину"),
                            ("code", "Промокод"),
                        ],
                        default="product",
                        max_length=10,
                        verbose_name="Тип скидки",
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=5)),
                ("is_percentage", models.BooleanField(default=True)),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True, related_name="discounts_related", to="shop.product"
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="cartitem",
            options={
                "verbose_name": "Элемент корзины",
                "verbose_name_plural": "Элементы корзины",
            },
        ),
        migrations.AddField(
            model_name="cart",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=10
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "product")},
        ),
        migrations.CreateModel(
            name="DiscountRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_quantity", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "min_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "discount",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cart.discount"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="price",
        ),
        migrations.AddField(
            model_name="cart",
            name="discount",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cart.discount",
            ),
        ),
    ]
