# Generated by Django 4.2.23 on 2025-08-17 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_discount_alter_cartitem_options_cart_total_price_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartitem",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="Цена"
            ),
        ),
    ]
