# Generated by Django 4.2.23 on 2025-08-17 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0006_alter_cartitem_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="price",
        ),
    ]
