# Generated by Django 4.2.23 on 2025-08-17 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0007_remove_cartitem_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="Цена"
            ),
        ),
    ]
