# Generated by Django 4.2.23 on 2025-08-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_rename_discount_active_product_is_on_sale_and_more"),
        ("cart", "0008_cartitem_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discountrule",
            name="discount",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="discount",
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                verbose_name="Цена на момент добавления",
            ),
        ),
        migrations.DeleteModel(
            name="Discount",
        ),
        migrations.DeleteModel(
            name="DiscountRule",
        ),
    ]
