# Generated by Django 4.2.23 on 2025-08-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0009_remove_discountrule_discount_remove_cart_discount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="is_selected",
            field=models.BooleanField(default=True, verbose_name="Выбран"),
        ),
    ]
