# Generated by Django 4.2.23 on 2025-08-17 22:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="discount_active",
        ),
        migrations.RemoveField(
            model_name="product",
            name="discount_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="discounts",
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Цена товара",
            ),
        ),
    ]
