# Generated by Django 4.2.23 on 2025-08-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0007_remove_cartitem_price"),
        ("shop", "0003_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_active",
            field=models.BooleanField(default=False, verbose_name="Скидка активна"),
        ),
        migrations.AddField(
            model_name="product",
            name="discount_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Цена со скидкой",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="discounts",
            field=models.ManyToManyField(
                blank=True,
                related_name="products_with_discount",
                to="cart.discount",
                verbose_name="Скидки",
            ),
        ),
    ]
