# Generated by Django 4.2.23 on 2025-08-18 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_product_discount_active_product_discount_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="discount_active",
        ),
        migrations.RemoveField(
            model_name="product",
            name="discount_price",
        ),
    ]
