# Generated by Django 4.2.23 on 2025-08-18 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_remove_product_discount_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_active",
            field=models.BooleanField(default=False, verbose_name="Скидка активна"),
        ),
        migrations.AddField(
            model_name="product",
            name="discount_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Цена со скидкой",
            ),
        ),
    ]
