# Generated by Django 4.2.23 on 2025-08-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_product_discount_active_product_discount_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="discount_active",
            new_name="is_on_sale",
        ),
        migrations.RemoveField(
            model_name="product",
            name="discount_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="discounts",
        ),
        migrations.AddField(
            model_name="product",
            name="old_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Старая цена (если есть скидка)",
            ),
        ),
    ]
