# Generated by Django 4.2.23 on 2025-08-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="steamid",
            field=models.CharField(
                blank=True,
                max_length=17,
                null=True,
                unique=True,
                verbose_name="Steam ID",
            ),
        ),
    ]
